mongodb:
    image: fiware/tutorials.tourguide-app.restaurant-data:20160504
    hostname: mongodb
    expose:
        - "27017"
    command: --smallfiles

orion:
    image: fiware/orion:latest
    hostname: orion
    links:
        - mongodb
    expose:
        - "1026"
    ports:
        - "1026:1026"
    command: -dbhost mongodb

authzforce:
    image: fiware/authzforce-ce-server:release-4.4.1b
    hostname: authzforce
    expose:
        - "8080"

idm:
    image: bitergia/idm-keyrock:5.1.0
    hostname: idm
    links:
        - authzforce
    volumes:
        - /config
    expose:
        - "5000"
    environment:
        - APP_NAME=TourGuide
        - AUTHZFORCE_VERSION=4.4.1b

idas:
    image: fiware/iotagent-ul:develop
    hostname: idas
    links:
        - mongodb:mongo
        - orion
    expose:
        - "7896"
        - "4041"
    ports:
        - "7896:7896"
        - "4041:4041"

ul20client:
    image: bitergia/ul20-client:latest
    hostname: ul20client
    links:
        - orion
        - idas
    command: --acpi
    environment:
        - UL20_IOTA_HOST=idas
        - UL20_IOTA_PORT=7896
        - UL20_IOTA_ADMIN_PORT=4041
        - UL20_API_KEY=tourguide-devices
        - UL20_SERVICE_NAME=tourguide

cygnus:
    image: bitergia/cygnus:develop
    links:
        - orion
    expose:
        - "5001"
        - "5002"
        - "5003"
        - "5050"
        - "6001"
    volumes:
        - ./docker/cygnus/subscriptions:/opt/subscribe
        - ./docker/cygnus/conf:/config

tourguide:
    image: fiware/tutorials.tourguide-app:latest
    hostname: tourguide
    links:
        - orion
        - idm
        - idas
    environment:
        - ORION_HOSTNAME=orion
        - ORION_NO_PROXY_HOSTNAME=orion
        - ORION_PORT=1026
        - ORION_PEP_ENABLED=false
        - IDAS_PORT=7896
        - IDAS_ADMIN_PORT=4041
        - IDAS_FIWARE_SERVICE=tourguide
        - IDAS_FIWARE_SERVICE_PATH=/
        - IDAS_API_KEY=tourguide-devices
        - ORION_SUBSCRIPTIONS_ENABLED=false
        - SENSORS_GENERATION_ENABLED=false
        - SENSORS_FORCED_UPDATE_ENABLED=false
    volumes_from:
        - idm
