mongodbdata:
    image: bitergia/fiware-devguide-restaurant-data:20151002
    volumes:
        - /data/db
    restart: no
    command: /bin/echo "Data-only container for mongodb."

mongodb:
    image: mongo:2.6
    volumes_from:
        - mongodbdata
    expose:
        - "27017"
    command: --smallfiles

orion:
    image: fiware/orion:latest
    links:
        - mongodb
    expose:
        - "1026"
    ports:
        - "1026:1026"
    command: -dbhost mongodb

authzforce:
    image: bitergia/authzforce:4.2.0
    expose:
        - "8080"

idm:
    image: bitergia/idm-keyrock:4.3.0
    links:
        - authzforce
    volumes:
        - /config
    expose:
        - "5000"
    environment:
        - APP_NAME=FIWAREdevGuide

pepwilma:
    image: bitergia/pep-wilma:4.3.0
    links:
        - orion
        - idm
        - authzforce
    volumes_from:
        - idm
    expose:
        - "1026"
    environment:
        - APP_HOSTNAME=orion
        - APP_PORT=1026

idasiotacpp:
    image: bitergia/idas-iota-cpp:1.2.0
    links:
        - mongodb
        - orion
    expose:
        - "8080"
        - "8081"

ul20client:
    image: bitergia/ul20-client:latest
    links:
        - orion
        - idasiotacpp:iota
    command: --acpi
    environment:
        - IOTA_PORT=8080

devguide:
    image: bitergia/fiware-devguide-app
    links:
        - orion
        - idm
        - pepwilma
        - idasiotacpp:idas
    environment:
        - ORION_HOSTNAME=pepwilma
        - ORION_NO_PROXY_HOSTNAME=orion
        - ORION_PORT=1026
        - ORION_PEP_ENABLED=true
    # volumes:
    #     - ~/devel/fiware/fiware-devguide-app:/home/bitergia/fiware-devguide-app
        - IDAS_PORT=8080
        - ORION_SUBSCRIPTIONS_ENABLED=false
    volumes_from:
        - idm
