mongodbdata:
    image: bitergia/fiware-devguide-restaurant-data:20150728
    volumes:
        - /data/db
    restart: no
    command: /bin/echo "Data-only container for mongodb."

mongodb:
    image: mongo:2.6
    volumes_from:
        - mongodbdata
    expose:
        - "27017"
    command: --smallfiles

orion:
    image: bitergia/fiware-orion:0.23.0
    links:
        - mongodb
    expose:
        - "1026"
    command: -fg

authzforce:
    image: bitergia/authzforce:4.2.0
    expose:
        - "8080"

idm:
    image: bitergia/idm-keyrock:4.3.0
    links:
        - authzforce
    volumes:
        - /config
    expose:
        - "5000"
    environment:
        - APP_NAME=FIWAREdevGuide

pepwilma:
    image: bitergia/pep-wilma:4.3.0
    links:
        - orion
        - idm
        - authzforce
    volumes_from:
        - idm
    expose:
        - "1026"
    environment:
        - APP_HOSTNAME=orion
        - APP_PORT=1026

devguide:
    image: bitergia/fiware-devguide-app
    links:
        - orion
        - idm
        - pepwilma
    environment:
        - ORION_HOSTNAME=pepwilma
        - ORION_PORT=1026
        - ORION_PEP_ENABLED=true
    # volumes:
    #  - ~/devel/fiware-devguide-app:/home/bitergia/fiware-devguide-app
    volumes_from:
        - idm
