mongodbdata:
    image: bitergia/fiware-devguide-restaurant-data:20150721
    volumes:
        - /var/lib/mongo
    restart: no
    entrypoint: ["/bin/echo","Data-only container for mongodb"]

mongodb:
    image: bitergia/mongodb:2.6
    volumes_from:
        - mongodbdata
    expose:
        - "27017"
orion:
    image: bitergia/fiware-orion:0.22.0
    links:
        - mongodb
    expose:
        - "10026"

authzforce:
    image: bitergia/authzforce:4.2.0
    expose:
        - "8080"

idm:
    image: bitergia/idm-keyrock:4.3.0
    links:
        - authzforce
    volumes:
        - /config
    expose:
        - "5000"
    environment:
        - APP_NAME=FIWAREdevGuide

devguide:
    image: bitergia/fiware-devguide-app
    links:
        - orion
        - idm
    # volumes:
    #     - ~/devel/fiware/fiware-devguide-app:/home/bitergia/fiware-devguide-app
    volumes_from:
        - idm
